### ISSUE TITLE
Verificar tamanho e crescimento da base de dados do relatório operacional

### ISSUE THREAD

**Issue by fjuniorr** [splor-mg/plano-atividades#3]
Checar inicialmente o tamanho dos arquivos extraídos via email (limite superior) e o tamanho do arquivo binário do qlikview.

**Comment by hslinhares** [comment]
O relatório operacional qlikview binário tem tamanho de 324MB, com dados de 2017 até o exercício atual.
Seus dados são provenientes de arquivos xls ou xlsx do armazém SIAFI e SIAD, da base reestimativa e tabelas auxiliares.
As bases do armazém do exercício corrente chegam diariamente por e-mail no gmail. Entre elas estão as bases dos fluxos de alterações orçamentárias, aprovação de cota orçamentária, crédito inicial e autorizado, execução (empenhado, liquidado e pago), receita arrecadada, restos a pagar e execução por item material (SIAD).
O armazém de dados tem a limitação de envio de 20MB por arquivo, por este motivo as bases de execução são divididas por mês. 
Todas as bases do exercício corrente são diariamente atualizadas, inclusive as bases de execução de meses anteriores, pelo fato de haver possibilidade de alteração no valor pago em meses passados.
As bases de exercícios anteriores são estáticas, ou seja, não precisam de atualização diária.
Todo o conjunto de dados somam atualmente 994MB sem considerar o arquivo binário de 324MB.
O crescimento anual do volume de dados fica entre 150MB a 200MB.
A discriminação completa dos dados utilizados com seus respectivos tamanhos consta anexa.
[bases_rel_operacional.xlsx](https://github.com/splor-mg/plano-atividades/files/11139464/bases_rel_operacional.xlsx)
